feat: сделал статистику
JustAlexB/java-explore-with-me pull request #3
Opened 2023-06-25 14:46 UTC by JustAlexB

2023-06-30 16:14 UTC, NikolaiDem requested changes

2023-06-30 16:14 UTC, NikolaiDem commented on stat-svc/stat-client/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Лучше ${project.version}
Аналогично в dependencies других pom-ников

2023-06-30 16:14 UTC, NikolaiDem commented on stat-svc/stat-server/src/main/java/ru/practicum/statserver/service/StatService.java
> +    List<ViewDto> getStat(LocalDateTime start, LocalDateTime end, String[] uris, boolean unique);
Аргументы “LocalDateTime start, LocalDateTime end, String[] uris, boolean unique” привлекательны для помещения их в dto класс. Все параметры лучше собрать в один dto.

2023-06-30 16:14 UTC, NikolaiDem commented on stat-svc/stat-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS statistics (
Еще лучше сделать таблицу с приложениями, где будет его id и название. Таким образом при изменении, например, названия приложения не придется обновлять всю таблицу statistics.

2023-08-04 12:05 UTC, JustAlexB commented on stat-svc/stat-client/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
надеюсь я правильно понял.

2023-08-07 19:33 UTC, NikolaiDem approved these changes

2023-08-07 19:33 UTC, NikolaiDem commented on stat-svc/stat-server/src/main/java/ru/practicum/statserver/controller/StatController.java
> +                                       @RequestParam(required = false, defaultValue = "false") boolean unique) {
При указании дефолтного значения можно не указывать required = false

2023-08-07 19:33 UTC, NikolaiDem commented on stat-svc/stat-server/src/main/java/ru/practicum/statserver/service/StatServiceImpl.java
> +            if (statParam.isUnique())
Кодстайл : добавить скобки {} для if/else

2023-08-07 19:33 UTC, NikolaiDem commented on stat-svc/stat-server/src/main/java/ru/practicum/statserver/repository/StatRepository.java
> +    @Query("select new ru.practicum.statdto.ViewDto(st.app, st.uri, count(distinct st.ip) as hits)" +
Все 4 запроса почти дублируются. Можно использовать jdbcTemplate для составления динамического запроса. Тогда и кода будет поменьше

2023-08-07 19:33 UTC, NikolaiDem commented on stat-svc/stat-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS statistics (
Окей, но при возможности лучше исправить)

2023-08-09 08:48 UTC, JustAlexB commented on stat-svc/stat-dto/src/main/java/ru/practicum/statdto/StatParamDto.java
> +@Data
согласен, косяк

2023-08-09 08:50 UTC, JustAlexB commented on stat-svc/stat-server/src/main/java/ru/practicum/statserver/service/StatServiceImpl.java
> +            if (statParam.isUnique())
меня за это уже когда-то били, но я привыкну.....скобки-скобки-скобки!

2023-08-11 01:51 UTC, JustAlexB commented
stat

2023-08-11 01:51 UTC, merged